### ISSUE TITLE
Generate static page

### ISSUE THREAD

**Issue by pepijndevos** [pepijndevos/LolItemSets#13]
We're getting closer and closer to something that basically works. We should at some point look into deploying the compiled JS to a _pages branch.

I tried to generate minified JS, but the json files would not load. I'm probably doing something stupid, or advanced optimisations are too advanced for me.

**Comment by aengelberg** [comment]
`:whitespace` and `:simple` optimizations work (reducing it down to one js file) but `:advanced` does not. After some rudimentary debugging I saw the resource fetcher is hanging. [This](https://groups.google.com/forum/#!topic/clojurescript/OqkjlpqKSQY) indicates that `clojure.browser.*` is not really for production use; maybe it breaks under advanced compilation.

**Comment by pepijndevos** [comment]
Ouch. Maybe we should use goog directly or use a Cljs library. What do you think?

**Comment by aengelberg** [comment]
I'm not very experienced in either option, but neither of them seem that hard. You could try cljs-http.

**Comment by pepijndevos** [comment]
It's working! http://pepijndevos.nl/LolItemSets/

**Comment by aengelberg** [comment]
Is there a workflow for this I can replicate on my machine? In case I want to recompile the production app.

**Comment by pepijndevos** [comment]
1. Run `lein cljsbuild once min`
2. Copy `resources/public`
3. Checkout `gh-pages`
4. Paste
5. Commit

So, not really a workflow, but it works. If you can think of something fancy with `git-subtree` and a lein task or Makefile, feel free.
