### ISSUE TITLE
Is there a point in choosing the champion name and level?

### ISSUE THREAD

**Issue by aengelberg** [pepijndevos/LolItemSets#15]
I would imagine that the differences between champions' raw stats are so negligible that they wouldn't affect the builds much. I suggest we either
- remove that field to fill in
- add at least one feature that can make the champion selection matter more, such as
  - provide gentle suggestions of what stats you should check (e.g. for Draven I probably want to go DPS)
  - somehow factor in champion passives that might skew their stats enough to affect the build (e.g. Morgana's passive spell vamp)
  - in the output item set, print out exactly what number each stat has. In that sense the champion does matter as you can factor their base stat into that equation in case the user cares.

**Comment by pepijndevos** [comment]
The latter for sure.

**Comment by pepijndevos** [comment]
Working on this, but needs some refactoring.

![screen shot 2015-08-23 at 11 10 08](https://cloud.githubusercontent.com/assets/168609/9427620/9bfa9dfa-4987-11e5-80ed-56cf23e4f962.png)
