### ISSUE TITLE
Show build properties

### ISSUE THREAD

**Issue by pepijndevos** [pepijndevos/LolItemSets#4]
It would be nice to show the total stats of the build. 

Can be adapted from print-results.

**Comment by aengelberg** [comment]
When this feature is implemented, users may want to be able to use the site to determine how much stats result from a specific build they specify. So we could think about allowing users to change the items in the build manually.

**Comment by pepijndevos** [comment]
Working on it right now.
![screen shot 2015-08-21 at 18 25 10](https://cloud.githubusercontent.com/assets/168609/9413413/056a35cc-4832-11e5-9791-f29feac6a2db.png)
