### ISSUE TITLE
Filter items

### ISSUE THREAD

**Issue by pepijndevos** [pepijndevos/LolItemSets#8]
We should filter out all the items that are unavailable on Summoners Rift or specific to a certain champion.

I don't want to see no more Lord Van Damm's Pillager.

**Comment by pepijndevos** [comment]
Also items that build into some other item could be removed. They only slow down the algorithm.

**Comment by aengelberg** [comment]
You could have a dynamic variable `*available-items*` that is bound depending on the UI.

**Comment by pepijndevos** [comment]
You mean in case you want to generate a Twisted Treeline build? In that case we could have a map variable in the reagent state that acts as a filter. There is a maps key on every item in which map it is available.

For now I'd suggest to stick to Summoners Rift, as that's what 99% of the people probably play. And even the other maps aren't _that_ different. The Pillager is pretty much a replacement for Infinity Edge.

Most other items I've seen that show up in builds where Bilgewater items that we don't want in any case.
